### ISSUE TITLE
Potentially bug in bounding box assignment

### ISSUE THREAD

**Issue by sirotenko** [kang205/STL-Dataset#1]
It looks like you have some issue with assigning a different bounding boxes for the same image.
For example, here's the index image f475bc86db12e719d27a1c440be35690 https://i.pinimg.com/originals/f4/75/bc/f475bc86db12e719d27a1c440be35690.jpg
If you search it in the https://raw.githubusercontent.com/kang205/STL-Dataset/master/fashion.json you'll find that it appears three times with a different corresponding product id but exactly same box [0.555024, 0.857252, 0.734733, 0.952618] which correspond to right lady's shoe.
Same issues could be found for other products (for example 4f2e5549a987f77c260117eed662cd14).
It looks like a result of some map-reduce job where boxes were keyed by product ids instead of product id + scene id

**Comment by chen-bowen** [comment]
I'm encountering the same issue here. could you help us fix it?

**Comment by kang205** [comment]
This is likely not a bug. As the data is from Pinterest Shop The Look, it's possible they provide multiple (similar or suitable) products for the same bounding box.

**Comment by sirotenko** [comment]
So you're saying that it couldn't be used for evaluation because any query image may correspond to some number of false negatives? I.e. we shouldn't use product id as ground truth label?

**Comment by kang205** [comment]
> So you're saying that it couldn't be used for evaluation because any query image may correspond to some number of false negatives? I.e. we shouldn't use product id as ground truth label?

I'm not sure if I understand this correctly. We don't treat the problem as a classification problem. We assume all the paired products are positive ones, and others are negative.

**Comment by sirotenko** [comment]
I mean the following. If there are three images of the *same product* where two of them have same ID and the third one have a different ID then the one with a different ID is a false negative.

**Comment by kang205** [comment]
Back to your original problem, I don't think there are issues where bbox is keyed by only product id. For example, product 2d0d720a12631db77d110e590195f3cb appears 3 times with different bounding box.

In summary, each scene may have several bbox, and each of the bbox may pair with several products.

However, indeed some labels (both bbox and scene-product pairs) are mislabeled, especially in Fashion. This is mainly due to the human labeling process, which I cannot solve. The label quality in Home Decor is much better. I hope this helps.
